---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshpiper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshpiper
  template:
    metadata:
      labels:
        app: sshpiper
    spec:
      serviceAccountName: sshpiper
      containers:
      - name: sshpiper
        image: lermit/sshpiper
        imagePullPolicy: Always
        env:
          - name: SSHPIPERD_UPSTREAM_DRIVER
            value: kubernetes

---
apiVersion: v1
kind: Service
metadata:
  name: sshpiper
spec:
  ports:
  - port: 2222
    targetPort: 2222
  selector:
    app: sshpiper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sshpiper
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sshpiper
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch", "get", "list"]
---
# This role binding allows "jane" to read pods in the "default" namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sshpiper
subjects:
- kind: ServiceAccount
  name: sshpiper
  namespace: romain
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: sshpiper
  apiGroup: rbac.authorization.k8s.io
